PROPAGATE_EXCEPTIONS = True
APP_DEV = True

# Database configuration
SQLALCHEMY_DATABASE_URI = 'sqlite:///convert.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SHOW_SQLALCHEMY_LOG_MESSAGES = False

# AWS Credentials
AWS_ACCESS_KEY = "ASIAXPWA7CPLVIA5BSNI"
AWS_SECRET_KEY = "cawKrL7FrWw/MR2k5LlB2q1HBS2mVmIld27Pnq9g"
AWS_SESSION_TOKEN = "FwoGZXIvYXdzEPz//////////wEaDOabvZUUM54geCMIGiLLAWv320101IhHihs7dRyAgG5w5D5tWhB+QW3KBE89qWrJ2Labh0gjMOc04sejHtbF7aki8N9hrOvxk3P4StaSGoK/+5yf6ghnBLSk+JUQ1y8EbdLJE2AnzgVvK5CGNIcCJVcbp1DPOBdOJ56yrD7oBNdDZ88ZfRTrijHemi+AukvffvrzBEPZ0DZ35CspTuhCbxZZwkLAX9oVYylnYUs64ldGmUkFHQ2zHsqxi4TvW+eM0E+qn3gI/cmL/RumAf8BIv/H1xaAUEyRm+PRKMzVi40GMi28V1xkTQKI+7H/N53ZjYCcI/cCxsftpqbqDQKuj6WEHA/lI4NMGw+Dopm659E="

# SQS
QUEUE_NAME = "consumers-queue.fifo"

# Bucket S3
S3_BUCKET_NAME = "filetransformer"
